services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sum
      POSTGRES_USER: sumuser
      POSTGRES_PASSWORD: sumpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    ports:
      - "8000:8000"
    build: ./backend/
    container_name: backend
    restart: always
    command: gunicorn setup.wsgi:application --bind 0.0.0.0:8000
    working_dir: /code/django-back-end
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "8080:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # TUDO na porta 80!
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data: