FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code/django-back-end  # ← CORRIGIR AQUI TAMBÉM!

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl -f http://localhost:8000/ || exit 1

CMD ["gunicorn", "setup.wsgi:application", "--bind", "0.0.0.0:8000"]