# Generated by Django 5.2.7 on 2025-10-16 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        ('escola', '0001_initial'),
        ('estudantes', '0001_initial'),
        ('professores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='professores.professor'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='escola.turma'),
        ),
        migrations.AddField(
            model_name='historicalatividade',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalatividade',
            name='professor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='professores.professor'),
        ),
        migrations.AddField(
            model_name='historicalatividade',
            name='turma',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='escola.turma'),
        ),
        migrations.AddField(
            model_name='historicalquestaobanco',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrespostaatividade',
            name='atividade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='atividades.atividade'),
        ),
        migrations.AddField(
            model_name='historicalrespostaatividade',
            name='estudante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estudantes.estudante'),
        ),
        migrations.AddField(
            model_name='historicalrespostaatividade',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividade',
            name='questoes',
            field=models.ManyToManyField(blank=True, to='atividades.questaobanco'),
        ),
        migrations.AddField(
            model_name='respostaatividade',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='atividades.atividade'),
        ),
        migrations.AddField(
            model_name='respostaatividade',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_atividades', to='estudantes.estudante'),
        ),
        migrations.AlterUniqueTogether(
            name='respostaatividade',
            unique_together={('atividade', 'estudante')},
        ),
    ]
