FROM python:3.11-slim

WORKDIR /app

# Atualiza pacotes e instala dependências do sistema para mysqlclient
RUN apt update && apt install -y \
    build-essential \
    default-libmysqlclient-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Atualiza pip, setuptools e wheel
RUN pip install --upgrade pip setuptools wheel

# Copia requirements e instala
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copia o restante do código
COPY . .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
