# Generated by Django 4.2.5 on 2025-08-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_historicaluser_options_alter_user_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='type',
            new_name='user_types',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='user_types',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_set', related_query_name='core_user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
