# Generated by Django 4.2.5 on 2025-09-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_type_historicaluser_user_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='user_types',
            new_name='user_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_types',
            new_name='user_type',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
